import Header from "../components/layouts/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <div className="layout-container flex h-full grow flex-col overflow-hidden">
        <Header />
        <div>{children}</div>
      </div>
    </div>
  );
}
