import Header from "./../components/layouts/Header";
import Sidebar from "./../components/layouts/Sidebar";

export const metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen max-h-screen bg-white">
      <div className="layout-container flex h-full grow flex-col overflow-hidden">
        <Header isLoggedIn={true} />
        <div className="flex p-4 overflow-hidden">
          <div className="hidden sm:flex pr-4">
            <Sidebar />
          </div>
          <div id="scroll" className="flex-1 overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
